#!/usr/bin/env python3
"""
从 https://models.dev/api.json 获取 LLM 价格数据，
生成 internal/price/presets.go 文件
"""

import json
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

LLM_PRICE_URL = "https://models.dev/api.json"

# 研发商及其自研模型系列前缀，过滤同一平台提供的第三方模型。
DEVELOPERS: dict[str, tuple[str, ...]] = {
    "openai": ("gpt", "o"),
    "anthropic": ("claude",),
    "google": ("gemini", "gemma", "lyria", "veo"),
    "deepseek": ("deepseek",),
    "xai": ("grok",),
    "alibaba": ("qwen", "qvq"),
    "zhipuai": ("glm",),
    "minimax": ("minimax",),
    "moonshotai": ("kimi",),
    "v0": ("v0",),
    "xiaomi": ("mimo",),
}

PRESETS_GO_TEMPLATE = '''package price

// Code generated by scripts/updatePrice.py. DO NOT EDIT.
// Last updated: {update_time}

import (
	"sync"

	"github.com/bestruirui/octopus/internal/model"
)

var llmPriceLock sync.RWMutex

var llmPrice = map[string]model.LLMPrice{{
{entries}
}}
'''


def fetch_price_data() -> dict:
    """从 API 获取价格数据"""
    req = urllib.request.Request(
        LLM_PRICE_URL, 
        headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"}
    )
    with urllib.request.urlopen(req) as response:
        return json.loads(response.read().decode("utf-8"))


def format_price(value: float | None) -> str:
    """格式化价格值，去除不必要的尾部零"""
    if value is None:
        return "0"
    if value == 0:
        return "0"
    # 使用 repr 避免浮点数精度问题，然后去除尾部零
    formatted = f"{value:.10f}".rstrip("0").rstrip(".")
    return formatted


def generate_entry(model_id: str, cost: dict) -> str:
    """生成单个模型的 Go map entry"""
    input_price = format_price(cost.get("input"))
    output_price = format_price(cost.get("output"))
    cache_read = format_price(cost.get("cache_read"))
    cache_write = format_price(cost.get("cache_write"))
    
    return f'\t"{model_id}": {{Input: {input_price}, Output: {output_price}, CacheRead: {cache_read}, CacheWrite: {cache_write}}},'


def main():
    print(f"Fetching price data from {LLM_PRICE_URL}...")
    raw_price = fetch_price_data()
    
    entries = []
    generated_model_ids = set()
    model_count = 0
    
    for provider, family_prefixes in DEVELOPERS.items():
        if provider not in raw_price:
            print(f"  Provider '{provider}' not found, skipping...")
            continue
            
        models = raw_price[provider].get("models", {})
        provider_count = 0
        
        for model_data in models.values():
            model_id = model_data.get("id", "").lower()
            model_family = model_data.get("family", "").lower()
            output_modalities = model_data.get("modalities", {}).get("output", [])
            cost = model_data.get("cost", {})
            
            if (
                not model_id
                or not model_family.startswith(family_prefixes)
                or "text" not in output_modalities
                or "embed" in model_id
                or "embed" in model_family
            ):
                continue

            if model_id in generated_model_ids:
                raise ValueError(f"Duplicate model ID after developer filtering: {model_id}")
            
            # 添加原始模型
            entries.append(generate_entry(model_id, cost))
            generated_model_ids.add(model_id)
            provider_count += 1
            
        print(f"  {provider}: {provider_count} models")
        model_count += provider_count
    
    # 生成 Go 文件内容
    update_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    content = PRESETS_GO_TEMPLATE.format(
        update_time=update_time,
        entries="\n".join(entries),
    )
    
    # 写入文件
    script_dir = Path(__file__).parent
    output_path = script_dir.parent / "internal" / "price" / "presets.go"
    
    output_path.write_text(content, encoding="utf-8")
    print(f"\nGenerated {output_path} with {model_count} models")


if __name__ == "__main__":
    main()
