name: build

on:
  push:

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: '11.10.0'
          cache: true
          cache_dependency_path: web/pnpm-lock.yaml

      - name: Build frontend
        working-directory: web
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Update price
        run: python3 scripts/updatePrice.py

      - name: Build backend
        run: go build -trimpath -tags=jsoniter .
